### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by schme** [szetk/OhHa-JavAllas#2]
Kloonattu 9.6 19:30

Oikein hyvältä näyttää. Plussaa kaavioiden ulkoasusta, oikein siistiä (Main ehkä hieman turha näyttää luokkakaaviossa).

Koodi siistiä, muuttujat hyvin nimetty ja luokat selkeästi jaettu osiin. Ainut muuttuja minkä jouduin tarkistamaan oli Pallon n. Se voisi hyvin olla vaikka numero. Unohdin tosin, että biljardipalloissa on numerot, joten saattoi olla vain omaa epäonnistumista.

En ole vektoreiden käyttöä törmäyksessä pahemmin tutkinut, joten en osaa kommentoida sen oikeellisuutta. Pallot tuntuvat kuitenkin pelatessa liikkuvan odotetusti ja tuntuma on hyvä.

Tykkään itse jakaa pelin säännöt ja pelialustan ominaisuudet omiin luokkiin. Peli luokka on melko pitkä. Jakaminen helpottaa uusien alustojen tekemistä ja sääntöjen erittelyä alustan ominaisuuksista. Joidenkin asioiden kanssa on tosin vaikea tehdä jakoa kumpaan ne laittaa. Yleensä pyrin pitämään säännöt Peli luokassa ja Alustassa fyysiset ominaisuudet: koko, mahdollisen gravitaation hallinta jne. Pisteytys, vuoron siirto yms taas Pelissä.

Eipä tähän ole paljon lisättävää. Olisin mielelläni pelaillut hieman enemmänkin, mutta ruudun blittailu teki huonon olon. Yritin miettiä mistä se johtuu, mutta en keksinyt mitään selkeätä vastausta. En tykkää oikein käyttää javan omia libraryja grafiikan suhteen muutenkaan, joten niiden tuntemus on hieman heikko.

**Comment by szetk** [comment]
Kiitoksia kommenteista! Tuo Peli-luokan jakaminen on pyörinyt pitkään mielessä, mutta en ole vielä keksinyt miten sen suorittaisin.
